### ISSUE TITLE
Mixpanel Tweaks Integration

### ISSUE THREAD

**Issue by SeptiK** [mixpanel/mixpanel-android-build#2]
Hi, i am trying to implement Tweaks Values as described in "Building with Tweak Annotations" section. But i  am getting "Error:Could not find com.mixpanel.android:annotations-compiler:1.0.0."

**Comment by joeatwork** [comment]
Sweet! Thanks for taking a look at this! Please be aware that server-side support for this isn't out yet (although, as you can tell, we're really close to it)- in fact, right now that version number "1.0.0" isn't accurate- you'll need to use version "0.1.0" since we haven't released it yet. (In the mean time, I'll fix the readme)

**Comment by joeatwork** [comment]
I'm really excited to hear what you do with this! If you need any help or have more comments, you're welcome to post them here OR contact me directly - my email address is joe AT mixpanel.com

**Comment by joeatwork** [comment]
I think this is resolved, I'm going to close this issue for now.
